-- Copyright 2016 The Cartographer Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- Cartographer configuration for LD06 LiDAR + Yesense H30 IMU (手持建图)
-- LD06: 5Hz, 360deg, range 0.02~30m, USB serial
-- IMU:  Yesense H30, 200Hz, AHRS orientation + angular_velocity + linear_acceleration
-- Mode: 2D SLAM with IMU for gravity alignment and motion compensation.
-- 3D point cloud generated by scan_to_3d.py, accumulated by octomap_server.

include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "base_link",
  published_frame = "base_link",
  odom_frame = "odom",
  provide_odom_frame = false,
  publish_frame_projected_to_2d = true,
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.1,      -- 子图发布周期：0.3→0.1，加快可视化更新
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.0,
  odometry_sampling_ratio = 1.0,
  fixed_frame_pose_sampling_ratio = 1.0,
  imu_sampling_ratio = 1.0,
  -- 外部里程计采样率：降低权重，让 Cartographer 更依赖激光匹配
  odometry_sampling_ratio = 0.5,
  landmarks_sampling_ratio = 1.0,
}

MAP_BUILDER.use_trajectory_builder_2d = true

-- ==================== 2D Trajectory Builder ====================

TRAJECTORY_BUILDER_2D.min_range = 0.02
TRAJECTORY_BUILDER_2D.max_range = 12.0
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 1.0

-- 禁用 Cartographer 内部 IMU：避免与外部 IMU 里程计冲突
-- 位姿估计由 imu_odom_publisher.py 主导，Cartographer 用激光匹配辅助校正
TRAJECTORY_BUILDER_2D.use_imu_data = false

-- 子图分辨率：手持场景用 0.05m
TRAJECTORY_BUILDER_2D.submaps.grid_options_2d.resolution = 0.05
-- 每个子图包含的 scan 数：LD06 5Hz → 35帧 ≈ 7秒
-- 子图：每 15 帧更新一次（LD06 5Hz → 3秒），让子图更快响应
TRAJECTORY_BUILDER_2D.submaps.num_range_data = 15

-- 运动滤波器：手持场景放宽，避免过快运动导致丢帧
-- max_time_seconds: 0.3s @ 5Hz ≈ 每 1.5 帧至少处理 1 帧
-- max_distance_meters: 0.1m
-- max_angle_radians: 2° (手持允许小幅度旋转)
-- 运动滤波器：手持场景放宽到极限，让每帧都参与建图
TRAJECTORY_BUILDER_2D.motion_filter.max_time_seconds = 0.1
TRAJECTORY_BUILDER_2D.motion_filter.max_distance_meters = 0.02
TRAJECTORY_BUILDER_2D.motion_filter.max_angle_radians = math.rad(0.5)

-- Ceres scan matcher：手持场景调整权重
-- rotation_weight 降低：允许更快旋转时仍收敛
-- translation_weight 保持：平移约束仍然重要
-- Ceres scan matcher：降低 occupied_space_weight，让稀疏点云也能匹配
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.occupied_space_weight = 2.0
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.translation_weight = 5.0
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.rotation_weight = 15.0

-- 实时相关扫描匹配器：手持场景启用，搜索窗口加大
-- 在线相关匹配器在低帧率雷达上比纯 Ceres 更鲁棒
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.linear_search_window = 0.2
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.angular_search_window = math.rad(20.0)
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.translation_delta_cost_weight = 10.0
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.rotation_delta_cost_weight = 1e-1

-- ==================== Global SLAM (回环检测) ====================

POSE_GRAPH.constraint_builder.min_score = 0.65
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.7
-- 每 25 个节点做一次全局优化
POSE_GRAPH.optimize_every_n_nodes = 25

-- 快速相关匹配器：回环检测用
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.linear_search_window = 7.0
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.angular_search_window = math.rad(30.0)
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.branch_and_bound_depth = 7

return options
