/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  factory_agent: () => import("@/views/factory_agent/index.vue"),
  factory_agv: () => import("@/views/factory_agv/index.vue"),
  factory_alarm: () => import("@/views/factory_alarm/index.vue"),
  factory_control: () => import("@/views/factory_control/index.vue"),
  factory_environment: () => import("@/views/factory_environment/index.vue"),
  factory_gas: () => import("@/views/factory_gas/index.vue"),
  factory_goods: () => import("@/views/factory_goods/index.vue"),
  factory_lighting: () => import("@/views/factory_lighting/index.vue"),
  factory_overview: () => import("@/views/factory_overview/index.vue"),
};
