/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'factory',
    path: '/factory',
    component: 'layout.base',
    meta: {
      title: 'factory',
      i18nKey: 'route.factory'
    },
    children: [
      {
        name: 'factory_agent',
        path: '/factory/agent',
        component: 'view.factory_agent',
        meta: {
          title: 'factory_agent',
          i18nKey: 'route.factory_agent'
        }
      },
      {
        name: 'factory_agv',
        path: '/factory/agv',
        component: 'view.factory_agv',
        meta: {
          title: 'factory_agv',
          i18nKey: 'route.factory_agv'
        }
      },
      {
        name: 'factory_alarm',
        path: '/factory/alarm',
        component: 'view.factory_alarm',
        meta: {
          title: 'factory_alarm',
          i18nKey: 'route.factory_alarm'
        }
      },
      {
        name: 'factory_control',
        path: '/factory/control',
        component: 'view.factory_control',
        meta: {
          title: 'factory_control',
          i18nKey: 'route.factory_control'
        }
      },
      {
        name: 'factory_environment',
        path: '/factory/environment',
        component: 'view.factory_environment',
        meta: {
          title: 'factory_environment',
          i18nKey: 'route.factory_environment'
        }
      },
      {
        name: 'factory_gas',
        path: '/factory/gas',
        component: 'view.factory_gas',
        meta: {
          title: 'factory_gas',
          i18nKey: 'route.factory_gas'
        }
      },
      {
        name: 'factory_goods',
        path: '/factory/goods',
        component: 'view.factory_goods',
        meta: {
          title: 'factory_goods',
          i18nKey: 'route.factory_goods'
        }
      },
      {
        name: 'factory_lighting',
        path: '/factory/lighting',
        component: 'view.factory_lighting',
        meta: {
          title: 'factory_lighting',
          i18nKey: 'route.factory_lighting'
        }
      },
      {
        name: 'factory_overview',
        path: '/factory/overview',
        component: 'view.factory_overview',
        meta: {
          title: 'factory_overview',
          i18nKey: 'route.factory_overview'
        }
      }
    ]
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
